name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make shellcheck ruby
        sudo gem install mdl

    - name: Run lint
      run: |
        touch .env # create empty env file to run the lint task
        make lint
